[package]
name = "cosmos"
version = "0.1.0"
authors = ["mabysh <max.byshnev@protonmail.com>"]

[dependencies]
nonblock = { git = "https://github.com/mabysh/nonblock-rs" }
tokio = "0.1.5"
termion = "1.5.1"
tui = "0.2.1"
env_logger = "0.5.7"
log = "0.4.0"
